key_values = {'Left mouse button': 1,
              'Right mouse button': 2,
              'Control-break processing': 3,
              'Middle mouse button (three-button mouse)': 4,
              'X1 mouse button': 5,
              'X2 mouse button': 6,
              'BACKSPACE key': 8,
              'TAB key': 9,
              'CLEAR key': 12,
              'ENTER key': 13,
              'SHIFT key': 16,
              'CTRL key': 17,
              'ALT key': 18,
              'PAUSE key': 19,
              'CAPS LOCK key': 20,
              'IME Kana mode': 21,
              'IME Hanguel mode (maintained for compatibility; use VK_HANGUL)': 21,
              'IME Hangul mode': 21,
              'IME On': 22,
              'IME Junja mode': 23,
              'IME final mode': 24,
              'IME Hanja mode': 25,
              'IME Kanji mode': 25,
              'IME Off': 26,
              'ESC key': 27,
              'IME convert': 28,
              'IME nonconvert': 29,
              'IME accept': 30,
              'IME mode change request': 31,
              'SPACEBAR': 32,
              'PAGE UP key': 33,
              'PAGE DOWN key': 34,
              'END key': 35,
              'HOME key': 36,
              'LEFT ARROW key': 37,
              'UP ARROW key': 38,
              'RIGHT ARROW key': 39,
              'DOWN ARROW key': 40,
              'SELECT key': 41,
              'PRINT key': 42,
              'EXECUTE key': 43,
              'PRINT SCREEN key': 44,
              'INS key': 45,
              'DEL key': 46,
              'HELP key': 47,
              '0 key': 48,
              '1 key': 49,
              '2 key': 50,
              '3 key': 51,
              '4 key': 52,
              '5 key': 53,
              '6 key': 54,
              '7 key': 55,
              '8 key': 56,
              '9 key': 57,
              'A key': 65,
              'B key': 66,
              'C key': 67,
              'D key': 68,
              'E key': 69,
              'F key': 70,
              'G key': 71,
              'H key': 72,
              'I key': 73,
              'J key': 74,
              'K key': 75,
              'L key': 76,
              'M key': 77,
              'N key': 78,
              'O key': 79,
              'P key': 80,
              'Q key': 81,
              'R key': 82,
              'S key': 83,
              'T key': 84,
              'U key': 85,
              'V key': 86,
              'W key': 87,
              'X key': 88,
              'Y key': 89,
              'Z key': 90,
              'Left Windows key (Natural keyboard)': 91,
              'Right Windows key (Natural keyboard)': 92,
              'Applications key (Natural keyboard)': 93,
              'Computer Sleep key': 95,
              'Numeric keypad 0 key': 96,
              'Numeric keypad 1 key': 97,
              'Numeric keypad 2 key': 98,
              'Numeric keypad 3 key': 99,
              'Numeric keypad 4 key': 100,
              'Numeric keypad 5 key': 101,
              'Numeric keypad 6 key': 102,
              'Numeric keypad 7 key': 103,
              'Numeric keypad 8 key': 104,
              'Numeric keypad 9 key': 105,
              'Multiply key': 106,
              'Add key': 107,
              'Separator key': 108,
              'Subtract key': 109,
              'Decimal key': 110,
              'Divide key': 111,
              'F1 key': 112,
              'F2 key': 113,
              'F3 key': 114,
              'F4 key': 115,
              'F5 key': 116,
              'F6 key': 117,
              'F7 key': 118,
              'F8 key': 119,
              'F9 key': 120,
              'F10 key': 121,
              'F11 key': 122,
              'F12 key': 123,
              'F13 key': 124,
              'F14 key': 125,
              'F15 key': 126,
              'F16 key': 127,
              'F17 key': 128,
              'F18 key': 129,
              'F19 key': 130,
              'F20 key': 131,
              'F21 key': 132,
              'F22 key': 133,
              'F23 key': 134,
              'F24 key': 135,
              'NUM LOCK key': 144,
              'SCROLL LOCK key': 145,
              'Left SHIFT key': 160,
              'Right SHIFT key': 161,
              'Left CONTROL key': 162,
              'Right CONTROL key': 163,
              'Left MENU key': 164,
              'Right MENU key': 165,
              'Browser Back key': 166,
              'Browser Forward key': 167,
              'Browser Refresh key': 168,
              'Browser Stop key': 169,
              'Browser Search key': 170,
              'Browser Favorites key': 171,
              'Browser Start and Home key': 172,
              'Volume Mute key': 173,
              'Volume Down key': 174,
              'Volume Up key': 175,
              'Next Track key': 176,
              'Previous Track key': 177,
              'Stop Media key': 178,
              'Play/Pause Media key': 179,
              'Start Mail key': 180,
              'Select Media key': 181,
              'Start Application 1 key': 182,
              'Start Application 2 key': 183,
              "Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the ';:' key": 186,
              "For any country/region, the '+' key": 187,
              "For any country/region, the ',' key": 188,
              "For any country/region, the '-' key": 189,
              "For any country/region, the '.' key": 190,
              "Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the '/?' key": 191,
              "Used for miscellaneous characters; it can vary by keyboard.  For the US standard keyboard, the '`~' key": 192,
              "Used for miscellaneous characters; it can vary by keyboard.  For the US standard keyboard, the '[{' key": 219,
              "Used for miscellaneous characters; it can vary by keyboard.  For the US standard keyboard, the '\\|' key": 220,
              "Used for miscellaneous characters; it can vary by keyboard.  For the US standard keyboard, the ']}' key": 221,
              "Used for miscellaneous characters; it can vary by keyboard.  For the US standard keyboard, the 'single-quote/double-quote' key": 222,
              'Used for miscellaneous characters; it can vary by keyboard.': 223,
              'Either the angle bracket key or the backslash key on the RT 102-key keyboard': 226,
              'IME PROCESS key': 229,
              'Used to pass Unicode characters as if they were keystrokes. The VK_PACKET key is the low word of a 32-bit Virtual Key value used for non-keyboard input methods. For more information, see Remark in KEYBDINPUT, SendInput, WM_KEYDOWN, and WM_KEYUP': 231,
              'Attn key': 246,
              'CrSel key': 247,
              'ExSel key': 248,
              'Erase EOF key': 249,
              'Play key': 250,
              'Zoom key': 251,
              'PA1 key': 253,
              'Clear key': 254}

key_constants = {'Left mouse button': 'VK_LBUTTON',
                 'Right mouse button': 'VK_RBUTTON',
                 'Control-break processing': 'VK_CANCEL',
                 'Middle mouse button (three-button mouse)': 'VK_MBUTTON',
                 'X1 mouse button': 'VK_XBUTTON1',
                 'X2 mouse button': 'VK_XBUTTON2',
                 'BACKSPACE key': 'VK_BACK',
                 'TAB key': 'VK_TAB',
                 'CLEAR key': 'VK_CLEAR',
                 'ENTER key': 'VK_RETURN',
                 'SHIFT key': 'VK_SHIFT',
                 'CTRL key': 'VK_CONTROL',
                 'ALT key': 'VK_MENU',
                 'PAUSE key': 'VK_PAUSE',
                 'CAPS LOCK key': 'VK_CAPITAL',
                 'IME Kana mode': 'VK_KANA',
                 'IME Hanguel mode (maintained for compatibility; use VK_HANGUL)': 'VK_HANGUEL',
                 'IME Hangul mode': 'VK_HANGUL',
                 'IME On': 'VK_IME_ON',
                 'IME Junja mode': 'VK_JUNJA',
                 'IME final mode': 'VK_FINAL',
                 'IME Hanja mode': 'VK_HANJA',
                 'IME Kanji mode': 'VK_KANJI',
                 'IME Off': 'VK_IME_OFF',
                 'ESC key': 'VK_ESCAPE',
                 'IME convert': 'VK_CONVERT',
                 'IME nonconvert': 'VK_NONCONVERT',
                 'IME accept': 'VK_ACCEPT',
                 'IME mode change request': 'VK_MODECHANGE',
                 'SPACEBAR': 'VK_SPACE',
                 'PAGE UP key': 'VK_PRIOR',
                 'PAGE DOWN key': 'VK_NEXT',
                 'END key': 'VK_END',
                 'HOME key': 'VK_HOME',
                 'LEFT ARROW key': 'VK_LEFT',
                 'UP ARROW key': 'VK_UP',
                 'RIGHT ARROW key': 'VK_RIGHT',
                 'DOWN ARROW key': 'VK_DOWN',
                 'SELECT key': 'VK_SELECT',
                 'PRINT key': 'VK_PRINT',
                 'EXECUTE key': 'VK_EXECUTE',
                 'PRINT SCREEN key': 'VK_SNAPSHOT',
                 'INS key': 'VK_INSERT',
                 'DEL key': 'VK_DELETE',
                 'HELP key': 'VK_HELP',
                 '0 key': '',
                 '1 key': '',
                 '2 key': '',
                 '3 key': '',
                 '4 key': '',
                 '5 key': '',
                 '6 key': '',
                 '7 key': '',
                 '8 key': '',
                 '9 key': '',
                 'A key': '',
                 'B key': '',
                 'C key': '',
                 'D key': '',
                 'E key': '',
                 'F key': '',
                 'G key': '',
                 'H key': '',
                 'I key': '',
                 'J key': '',
                 'K key': '',
                 'L key': '',
                 'M key': '',
                 'N key': '',
                 'O key': '',
                 'P key': '',
                 'Q key': '',
                 'R key': '',
                 'S key': '',
                 'T key': '',
                 'U key': '',
                 'V key': '',
                 'W key': '',
                 'X key': '',
                 'Y key': '',
                 'Z key': '',
                 'Left Windows key (Natural keyboard)': 'VK_LWIN',
                 'Right Windows key (Natural keyboard)': 'VK_RWIN',
                 'Applications key (Natural keyboard)': 'VK_APPS',
                 'Computer Sleep key': 'VK_SLEEP',
                 'Numeric keypad 0 key': 'VK_NUMPAD0',
                 'Numeric keypad 1 key': 'VK_NUMPAD1',
                 'Numeric keypad 2 key': 'VK_NUMPAD2',
                 'Numeric keypad 3 key': 'VK_NUMPAD3',
                 'Numeric keypad 4 key': 'VK_NUMPAD4',
                 'Numeric keypad 5 key': 'VK_NUMPAD5',
                 'Numeric keypad 6 key': 'VK_NUMPAD6',
                 'Numeric keypad 7 key': 'VK_NUMPAD7',
                 'Numeric keypad 8 key': 'VK_NUMPAD8',
                 'Numeric keypad 9 key': 'VK_NUMPAD9',
                 'Multiply key': 'VK_MULTIPLY',
                 'Add key': 'VK_ADD',
                 'Separator key': 'VK_SEPARATOR',
                 'Subtract key': 'VK_SUBTRACT',
                 'Decimal key': 'VK_DECIMAL',
                 'Divide key': 'VK_DIVIDE',
                 'F1 key': 'VK_F1',
                 'F2 key': 'VK_F2',
                 'F3 key': 'VK_F3',
                 'F4 key': 'VK_F4',
                 'F5 key': 'VK_F5',
                 'F6 key': 'VK_F6',
                 'F7 key': 'VK_F7',
                 'F8 key': 'VK_F8',
                 'F9 key': 'VK_F9',
                 'F10 key': 'VK_F10',
                 'F11 key': 'VK_F11',
                 'F12 key': 'VK_F12',
                 'F13 key': 'VK_F13',
                 'F14 key': 'VK_F14',
                 'F15 key': 'VK_F15',
                 'F16 key': 'VK_F16',
                 'F17 key': 'VK_F17',
                 'F18 key': 'VK_F18',
                 'F19 key': 'VK_F19',
                 'F20 key': 'VK_F20',
                 'F21 key': 'VK_F21',
                 'F22 key': 'VK_F22',
                 'F23 key': 'VK_F23',
                 'F24 key': 'VK_F24',
                 'NUM LOCK key': 'VK_NUMLOCK',
                 'SCROLL LOCK key': 'VK_SCROLL',
                 'Left SHIFT key': 'VK_LSHIFT',
                 'Right SHIFT key': 'VK_RSHIFT',
                 'Left CONTROL key': 'VK_LCONTROL',
                 'Right CONTROL key': 'VK_RCONTROL',
                 'Left MENU key': 'VK_LMENU',
                 'Right MENU key': 'VK_RMENU',
                 'Browser Back key': 'VK_BROWSER_BACK',
                 'Browser Forward key': 'VK_BROWSER_FORWARD',
                 'Browser Refresh key': 'VK_BROWSER_REFRESH',
                 'Browser Stop key': 'VK_BROWSER_STOP',
                 'Browser Search key': 'VK_BROWSER_SEARCH',
                 'Browser Favorites key': 'VK_BROWSER_FAVORITES',
                 'Browser Start and Home key': 'VK_BROWSER_HOME',
                 'Volume Mute key': 'VK_VOLUME_MUTE',
                 'Volume Down key': 'VK_VOLUME_DOWN',
                 'Volume Up key': 'VK_VOLUME_UP',
                 'Next Track key': 'VK_MEDIA_NEXT_TRACK',
                 'Previous Track key': 'VK_MEDIA_PREV_TRACK',
                 'Stop Media key': 'VK_MEDIA_STOP',
                 'Play/Pause Media key': 'VK_MEDIA_PLAY_PAUSE',
                 'Start Mail key': 'VK_LAUNCH_MAIL',
                 'Select Media key': 'VK_LAUNCH_MEDIA_SELECT',
                 'Start Application 1 key': 'VK_LAUNCH_APP1',
                 'Start Application 2 key': 'VK_LAUNCH_APP2',
                 "Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the ';:' key": 'VK_OEM_1',
                 "For any country/region, the '+' key": 'VK_OEM_PLUS',
                 "For any country/region, the ',' key": 'VK_OEM_COMMA',
                 "For any country/region, the '-' key": 'VK_OEM_MINUS',
                 "For any country/region, the '.' key": 'VK_OEM_PERIOD',
                 "Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the '/?' key": 'VK_OEM_2',
                 "Used for miscellaneous characters; it can vary by keyboard.  For the US standard keyboard, the '`~' key": 'VK_OEM_3',
                 "Used for miscellaneous characters; it can vary by keyboard.  For the US standard keyboard, the '[{' key": 'VK_OEM_4',
                 "Used for miscellaneous characters; it can vary by keyboard.  For the US standard keyboard, the '\\|' key": 'VK_OEM_5',
                 "Used for miscellaneous characters; it can vary by keyboard.  For the US standard keyboard, the ']}' key": 'VK_OEM_6',
                 "Used for miscellaneous characters; it can vary by keyboard.  For the US standard keyboard, the 'single-quote/double-quote' key": 'VK_OEM_7',
                 'Used for miscellaneous characters; it can vary by keyboard.': 'VK_OEM_8',
                 'Either the angle bracket key or the backslash key on the RT 102-key keyboard': 'VK_OEM_102',
                 'IME PROCESS key': 'VK_PROCESSKEY',
                 'Used to pass Unicode characters as if they were keystrokes. The VK_PACKET key is the low word of a 32-bit Virtual Key value used for non-keyboard input methods. For more information, see Remark in KEYBDINPUT, SendInput, WM_KEYDOWN, and WM_KEYUP': 'VK_PACKET',
                 'Attn key': 'VK_ATTN',
                 'CrSel key': 'VK_CRSEL',
                 'ExSel key': 'VK_EXSEL',
                 'Erase EOF key': 'VK_EREOF',
                 'Play key': 'VK_PLAY',
                 'Zoom key': 'VK_ZOOM',
                 'PA1 key': 'VK_PA1',
                 'Clear key': 'VK_OEM_CLEAR'}
